version: '3.8'

services:
  kotlin-spring-boot-app:
    image: kotlin-spring-boot-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
